export const greetings = [
    "Hello, how are you today?",
    "Hi there! Hope you're having a great day.",
    "Good morning! What can I do for you?",
    "Hey! How's it going?",
    "Greetings! How can I assist you?",
    "Hello! Nice to see you.",
    "Hi! What’s up?",
    "Welcome! How may I help you today?",
    "Hey there! Need any help?",
    "Good evening! How are you feeling today?",
    "Howdy! What’s new with you?",
    "Hi! It’s great to see you.",
    "Hello there! How’s everything?",
    "Hey! How can I make your day better?",
    "Greetings! What brings you here today?",
    "Hello! What’s on your mind?",
    "Hi there! What’s happening?",
    "Good day! How can I support you?",
    "Hey! Got any plans for today?",
    "Welcome back! How’s it going?",
    "Hello! What can I do for you right now?",
    "Hi! How can I be of service?",
];